### ISSUE TITLE
Can't use alt for triggerbot bind.

### ISSUE THREAD

**Issue by meta-Lord** [martinjanas/Sensum#101]
Sensum's version: 1.5.6

Problem description: I am not able to set alt as my bind for triggerbot. Could someone help me out with how to fix this.

**Comment by p1pS** [comment]
Doesn't work for me either. What you can do is go into the globals.json file in the config directory and set the `globals.binds.trigger` to 18 (which is alt) full list:
[here](http://nehe.gamedev.net/article/msdn_virtualkey_codes/15009/)
