### ISSUE TITLE
Cant compile

### ISSUE THREAD

**Issue by Froro320** [martinjanas/Sensum#103]
ifndef _SILENCE_EXPERIMENTAL_FILESYSTEM_DEPRECATION_WARNING#error The header providing std::experimental::filesystem is deprecated by Microsoft \and will be REMOVED. It is superseded by the C++17 header providing std::filesystem. \You can define _SILENCE_EXPERIMENTAL_FILESYSTEM_DEPRECATION_WARNING to acknowledge that you have received this warning.#endif // _SILENCE_EXPERIMENTAL_FILESYSTEM_DEPRECATION_WARNING

**Comment by armyvagyok** [comment]
replace all of std::experimental::filesystem with std::filesystem

**Comment by Froro320** [comment]
still doesnt work
