### ISSUE TITLE
Skins

### ISSUE THREAD

**Issue by Geerphy** [martinjanas/Sensum#11]
Please add Crimson web, Fade and Forest DDPAT skins for knife and The Emperor skin for M4A4.

**Comment by martinjanas** [comment]
Im busy, Handling with work stuff in IRL,dont have much time.

You can manually edit the skins file and then add the skin ID to the weapon ID

Search for weapon id & skins id

**Comment by Geerphy** [comment]
Okey chill, i added all of the skins to game-items. ;)
