### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Falmze** [martinjanas/Sensum#120]
Can someone help me fix this error?
![Capture](https://user-images.githubusercontent.com/58751308/76725511-8f042d80-67a2-11ea-9d85-c315493b4121.PNG)

**Comment by 3Ld4D** [comment]
did you try to change <experimental/filesystem> to <filesystem>?

**Comment by Falmze** [comment]
what?

**Comment by eelimake** [comment]
> what?

Change the #include <experiemental/filesystem> to #include <filesystem> and change the namespace fs = std::experimental::filesystem; to namespace fs = std::filesystem; in both files (config.cpp and options.cpp).
Should work.
