### ISSUE TITLE
Change Hook Method

### ISSUE THREAD

**Issue by AlexanderQueen** [martinjanas/Sensum#134]
Why you don't try to change hooking method? It a great project to left it behind.

**Comment by martinjanas** [comment]
I changed the hooking method, but I decided to make it private.

**Comment by newcommerdontblame** [comment]
> I changed the hooking method, but I decided to make it private.

dude pls invite to ur discord or share dll with us pls

**Comment by AlexanderQueen** [comment]
Make a discord channel and left here invite/or if you have invite us.

**Comment by newcommerdontblame** [comment]
> Make a discord channel and left here invite/or if you have invite us.

yes man please))
