### ISSUE TITLE
Can't Compile.

### ISSUE THREAD

**Issue by gamer6969** [martinjanas/Sensum#139]
Sensum's version: Latest version

Problem description: Can't compile due to "Cannot open source file:" errors, help?

**Comment by martinjanas** [comment]
Please, dont make issue, just because you are lazy to google how to fix this trivial error.

Next time dont write "Latest version", if this would be real issue, I wouldnt know which version was causing problems.

**Comment by gamer6969** [comment]
Latest version means the one i downloaded a second ago, also i googled and havent found an answer.

**Comment by martinjanas** [comment]
> Latest version means the one i downloaded a second ago, also i googled and havent found an answer.

Just for example: If you would make an issue about aimbot not working and you would write: "Sensum version: latest version" and I would look at that issue 6 months later, I wouldnt know which version was latest version.

If one of the includes errors are saying something about d3d9.h just visit this link below, else if its not d3d9.h just delete the line with the include.

https://guidedhacking.com/threads/cannot-open-include-file-d3dx9-h-no-such-file-or-directory.7925/

**Comment by gamer6969** [comment]
Ok thanks so much!

**Comment by gamer6969** [comment]
Fixed it by reinstalling Sensum thank you for help.
