### ISSUE TITLE
Crashes a lot.

### ISSUE THREAD

**Issue by gamer6969** [martinjanas/Sensum#140]
Version:  1.7.0
Problem: The cheat crashes a lot, maybe because of the big junkcode?

**Comment by martinjanas** [comment]
I will investigate that, please send me your configs so I can debug with 100% accuracy as you had.

**Comment by gamer6969** [comment]
https://anonfiles.com/X622q0bbp3/bruh

**Comment by gamer6969** [comment]
^ my config

**Comment by harshraj21** [comment]
I havent found any crashes yet been using since release...
