### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Felix5k** [martinjanas/Sensum#15]
I think it's need a update

**Comment by martinjanas** [comment]
Update these in csgostructs.cpp
UpdateClientSideAnimation 222
GetCSWpnData 455
GetSpread 447
GetInaccuracy 477
UpdateAccuracyPenalty 478
IsPlayer 156
EyePos 282
IsWeapon 164

**Comment by DarixonSK** [comment]
I don´t know nothing about csgostructs.cpp. Where I can find new dll? :D for this update @martinjanas

**Comment by GunSlingerEAC** [comment]
> I don´t know nothing about csgostructs.cpp. Where I can find new dll? :D for this update @martinjanas

legit open the sensum project find the csgostructs.cpp file and edit it you're pretty much updating offsets

**Comment by Geerphy** [comment]
What line is on GetCSWpnData?

**Comment by Geerphy** [comment]
I cant find it

**Comment by p-lok** [comment]
> What line is on GetCSWpnData?

should be ~210, the it's called "get_weapon_data()"
also i didn't have to update GetEyePos() because its dynamic already.

**Comment by Geerphy** [comment]
When i updated csgostructs.cpp, csgo crashing again....

**Comment by Felix5k** [comment]
i have updated csgostructs.cpp but i get crashed again..

În sâm., 21 sept. 2019 la 08:53, Geerphy <notifications@github.com> a scris:

**Comment by Felix5k** [comment]
CAN YOU UPDATE THE SOURCE?

**Comment by martinjanas** [comment]
Im going to update it.


-New backtrack will be removed, backtrack chams will be removed, for fps issues.

**Comment by Felix5k** [comment]
thanks

**Comment by Felix5k** [comment]
you can late backtrack..

**Comment by Felix5k** [comment]
i have tested the sensum old version and that do not crash..

**Comment by martinjanas** [comment]
Updated.
