### ISSUE TITLE
[HELP] How to add Watermark?

### ISSUE THREAD

**Issue by OdogWare187** [martinjanas/Sensum#155]

**Comment by martinjanas** [comment]
imdraw::outlined_text("Sensum", ImVec2(x_pos, y_pos), white_color);

**Comment by OdogWare187** [comment]
> imdraw::outlined_text("Sensum", ImVec2(x_pos, y_pos), white_color);

thanks you but it make 2 errors,
imdraw & outlined_text.

I'm learning c++ but Imgui is hard for me.

**Comment by PixelGM** [comment]
dude's want to sell paste to his friend :)
