### ISSUE TITLE
Should I remove the new backtrack & backtrack chams? It has perf bugs. LET ME KNOW

### ISSUE THREAD

**Issue by martinjanas** [martinjanas/Sensum#16]
The new backtrack has no legit backtrack option, new backtrack has fps issues.

Let me know if you want to remove it.

**Comment by Geerphy** [comment]
Bro, please add a Griefing box its a good features! ;) #CZSKPower :D

**Comment by trollman4444** [comment]
Yeah, you should.

**Comment by Ebzdyberybencjusz** [comment]
U should add better triggerbot

**Comment by martinjanas** [comment]
> Bro, please add a Griefing box its a good features! ;) #CZSKPower :D

I wont be adding griefing box, there's "dmg" indicator in players tab. 300 dmg to be kicked.

**Comment by martinjanas** [comment]
> U should add better triggerbot

It is already a good triggerbot, magnet triggerbot.

**Comment by Ebzdyberybencjusz** [comment]
> > U should add better triggerbot
> 
> It is already a good triggerbot, magnet triggerbot.

which uses fov from aimbot, you should add a separate fov slider to triggerbot
