### ISSUE TITLE
Sensum crashing when joining a game

### ISSUE THREAD

**Issue by Samppa401** [martinjanas/Sensum#161]
Version: 1.10

Details: Boot up game, tried with two injectors, load config, enter game crashes on final stages of loading screen. I think the issue is in the offsets but I don't really know, I'll try one more injector and also not loading the config. I don't understand the code enough to know where the offsets are at so I could update them with a dumper.

Edit: I injected without enabling anything and I got into the game but it crashed shortly after (I didn't do anything).

**Comment by leoireo** [comment]
I still got the old source code to it, but I finally made my own cheat that is 10x better than this

**Comment by 90th** [comment]
> I still got the old source code to it, but I finally made my own cheat that is 10x better than this

who asked...

**Comment by martinjanas** [comment]
Fixed.
