### ISSUE TITLE
Get banned by server's antiDLL

### ISSUE THREAD

**Issue by cfprovip** [martinjanas/Sensum#169]
Sensum version: 1.12.10
Problem description: Get banned by server's antiDLL

Hi. I have this server: 103.9.158.241:27019
This is a non-prime server and I used to be able to play here with sensum
But recently the server is updated with something called AntiDLL: https://github.com/JDW1337/AntiDLL/
AntiDLL detects DLL injected into CS:GO and ban anyone attempting to enter the server with cheats

So I cannot use sensum anymore. The server immediately gives me a permanent ban the moment I try to connect
![image](https://user-images.githubusercontent.com/82202157/114141499-da542580-993b-11eb-857a-015be50fc7b7.png)

After some researchs I found that AntiDLL seems to detect `item_purchase` and `bullet_impact` event listeners: https://github.com/danielkrupinski/Osiris/issues/2758

The owner of Osiris has already fixed this issue with an update

Sensum is my favourite cheats so I hope you make an update too

Thanks!

**Comment by martinjanas** [comment]
Sorry, I dont support cheating on community servers, closed.
