### ISSUE TITLE
Fast Stop: Making player moving slowly to the opposite direction

### ISSUE THREAD

**Issue by hungdz1234** [martinjanas/Sensum#170]
Sensum version: 1.15.00
Problem description:
- Fast Stop: Fast Stop makes me move slowly towards the opposite direction
- RCS is not working
- Glow is not enabled but dropped weapon still glows

**Comment by martinjanas** [comment]
#1 - There's no such version as "1.15.00".
#2 - Micromovements with fast stop was fixed in latest update.
#3 - RCS is working.

Closed.
