### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by PurpX** [martinjanas/Sensum#177]
I need help, I'm fairly new to coding and am just trying to help a mate out
I have spent over 3 hours trying to figure out why I am getting this error

Have tried multiple times to install DX9 and copy and paste into projects folder I have tried multiple fixes online but still have the problem with: Cannot open include file: 'd3dx9.h'

Please help!!

![image](https://user-images.githubusercontent.com/63692966/116977010-ff0ea380-ad15-11eb-8769-8be30f587ff0.png)

**Comment by PixelGM** [comment]
nice brain
