### ISSUE TITLE
Fast  Stop  issuses 

### ISSUE THREAD

**Issue by BadAtCSGO** [martinjanas/Sensum#187]
Problem: Version 1.9  
The  Fast Stop  makes  me slide  slowly.  Assuming I run, stop, then I slide forward. If I move to the left and stop, I slide to the left. Relatively slow, but annoying

Video  down  below: 

https://streamable.com/kfe2bg

You see it best  when im in the menu
Greatz!

**Comment by martinjanas** [comment]
You are using old version, has been fixed 1 month ago.
