### ISSUE TITLE
RCS crosshair has multiple issues

### ISSUE THREAD

**Issue by pranaypratyush** [martinjanas/Sensum#191]
version: 1.12.12
RCS crosshair isn't shown with some combination of settings (yet to pinpoint the exact combo) 
Even when it does work it appears midway between crosshair position and angle/point at which bullet is actually going to hit.

**Comment by martinjanas** [comment]
I know about this.

**Comment by pranaypratyush** [comment]
can you help with what's causing this? I would help with code.
