### ISSUE TITLE
Aimbot tracks till body boundary

### ISSUE THREAD

**Issue by pranaypratyush** [martinjanas/Sensum#192]
version: 1.12.12
Aimbot with snipers (with smooth 1.0) doesn't work for the first shot. The crosshair ends up at the boundary of the body and doesn't register. Clicking a second time without moving the mouse registers a hit.

**Comment by martinjanas** [comment]
Thats because Createmove is 1 tick behind, turning silent on will fix this.

**Comment by pranaypratyush** [comment]
Silent is already on.

**Comment by martinjanas** [comment]
Just tested this with smooth 1, backtrack 1 tick and with and without silent, the aimbot locks on first shot without no problems.

**Comment by pranaypratyush** [comment]
works without silent but not with it. is this expected? Also why did you test with backtrack 1 tick and not let's say 6?

**Comment by pranaypratyush** [comment]
first file is my settings
second is where I aim just before clicking. Notice the white circle thats the fov
third is where it hit. 

![Untitled](https://user-images.githubusercontent.com/10587083/121127503-7f5d8280-c847-11eb-9b73-b2a6d23e54a8.png)
![Untitled1](https://user-images.githubusercontent.com/10587083/121127513-81bfdc80-c847-11eb-8004-f856dfdb865d.png)
![Untitled2](https://user-images.githubusercontent.com/10587083/121127524-85ebfa00-c847-11eb-9b4e-5acfe79c7392.png)
