### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by alexezz21** [martinjanas/Sensum#195]
Sensum 1.12.14:
Localplayer is bugged and shows the enemies/teammates characters in the right or the left, they dont look in the right way!

**Comment by martinjanas** [comment]
Hi, could You take a screenshot with this in action?

**Comment by martinjanas** [comment]
@alexezz21 Please respond.

**Comment by alexezz21** [comment]
Sorry didn't see. I will 
![image](https://user-images.githubusercontent.com/75838132/124511585-2f8ac080-dddf-11eb-9db4-a88b74af6a67.png)
They don't look in that way!

**Comment by martinjanas** [comment]
Turn off resolver.
