### ISSUE TITLE
crashing game when I enter a match

### ISSUE THREAD

**Issue by sleepyxdev** [martinjanas/Sensum#20]
The game crashes everytime I join a game, I injected after joining the game it worked fine then crashed when I died I have also tried debugging to see what's wrong but it crashes instantly when injecting on debug. (running the game on fullscreen windowed mode if that matters)

**Comment by p-lok** [comment]
what did you change in the cheat; that'll help narrow down the problem.

**Comment by martinjanas** [comment]
> what did you change in the cheat; that'll help narrow down the problem.

https://github.com/martinjanas/Sensum/commits/master

**Comment by sleepyxdev** [comment]
> what did you change in the cheat; that'll help narrow down the problem.

haven't changed anything important except the name
