### ISSUE TITLE
Sensum version: 1.13.8 doesn't work after latest cs go update

### ISSUE THREAD

**Issue by ZGTX1** [martinjanas/Sensum#203]
Sensum version: 1.13.8
Problem description: most of the options doesn't work after latest cs goupdate, grenade prediction instantly crashes game. 
aimbot, box, recoil control failed completly

**Comment by ZGTX1** [comment]
i meant cs go update

**Comment by PixelGM** [comment]
I just pulled a req for the fix, just waiting to get accepted ;)

**Comment by ZGTX1** [comment]
> I just pulled a req for the fix, just waiting to get accepted ;)

Cool :D I've  seen your release i think. You got star from me 👍

**Comment by PixelGM** [comment]
> > I just pulled a req for the fix, just waiting to get accepted ;)
> 
> Cool :D I've  seen your release i think. You got star from me 👍 

Enjoy :D
