### ISSUE TITLE
crashes

### ISSUE THREAD

**Issue by ZGTX1** [martinjanas/Sensum#205]
crashes on dust2, i haven't on other  maps yet
edit: other maps too
BOTS work fine  but online crashes

**Comment by Apoctri** [comment]
Yeah... It works on workshop maps, and bots and the cheat features are completely fine and working.
I thought it was something in my configs, so I deleted my configs but it still crashes, I don't need to update my windows as well
It only crashes on online matches for some weird unknown reason, im pretty glad I ain't the only one to experience the same problem

**Comment by Apoctri** [comment]
@ZGTX1 Does it work now? Or does it still crash, if it works then maybe you can help me.

**Comment by ZGTX1** [comment]
Still no clue. I tried many things Like reinstalling CS go, reinstalling windows from diffrent ISO, deleted configs, also tried to join with all options disabled. When playing bots i discovered that even when all options arę disabled weapon glow still works

**Comment by ZGTX1** [comment]
I will try combining older versions with latest and see. It's stupid but worth trying. Wait for results 😋

**Comment by Apoctri** [comment]
That's what I also had in mind, installing older versions and whatnot, I'm not really sure if it is an offset problem or not, as far as im concerned it isn't an injector problem nor a vac bypass problem. Installing older versions tho might take me a while since I have no time for it at all. Thanks for the hard work.

**Comment by Apoctri** [comment]
And I'm not sure either if this issue might be fixed now or like after a bit of time, since this update pretty much destroyed the sensum thing, some cheats do work, but sensum is literally the best legit cheat I have had for like half a year now.

**Comment by ZGTX1** [comment]
I have a version that most of functions work but crashes sometimes i can send you a dll od you want

**Comment by ZGTX1** [comment]
https://mega.nz/file/p5UQlDBa#kTEjwY03UcoFqrk1uTq9kApGjODydhOEHaUgBNjUEPA

**Comment by Apoctri** [comment]
Yeah, that will be helpful, I will try it after I get back from school (probably)

**Comment by Apoctri** [comment]
Meh, the functions don't work at all, as soon as I load a config it just crashes. I tried to rebuild sensum again, it still crashes, now I'm pretty sure it is the „sensum.dll" problem, since I also tried other injectors, and still crashes.

**Comment by eigthguy8** [comment]
still crashing when is online i tried all the solutions possible but i could not doing anything

**Comment by Apoctri** [comment]
We just have to wait until @martinjanas fixes it, I thought we could find alternative ways to fix it but looks like just the devs can do a thing about it.
Just wait for it.

**Comment by martinjanas** [comment]
I have just pushed an update, sorry guys for the delay.I had something in the repo on my hardrive I have been working on and couldnt push an update.

Let me know if you encounter any more crashes or bugs.

**Comment by Apoctri** [comment]
I downloaded the new one, which was like 3 hours ago, while building it I got these 3 errors and 7 warnings @martinjanas 
![Screenshot 2021-10-01 171316](https://user-images.githubusercontent.com/91519775/135644842-3b67d6fa-21c4-4dd6-8809-46bdd9fd12ef.png)

**Comment by martinjanas** [comment]
@Apoctri Fixed.Visual Studio is acting weird, it let me compile without problems...

**Comment by ZGTX1** [comment]
> I downloaded the new one, which was like 3 hours ago, while building it I got these 3 errors and 7 warnings @martinjanas ![Screenshot 2021-10-01 171316](https://user-images.githubusercontent.com/91519775/135644842-3b67d6fa-21c4-4dd6-8809-46bdd9fd12ef.png)

![image](https://user-images.githubusercontent.com/91291242/135652828-f873610e-52d4-4883-9e21-802ee0e69e3c.png)

**Comment by ZGTX1** [comment]
> @Apoctri Fixed.Visual Studio is acting weird, it let me compile without problems...

thank you for your work <3

**Comment by Apoctri** [comment]
@martinjanas it still crashes when loading into offline matches.

**Comment by Apoctri** [comment]
Like, at the end of the map loading thing, it just crashes

**Comment by Apoctri** [comment]
I mean online matches not offline
