### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by FriXeee** [martinjanas/Sensum#216]
have random crash after 1 match or when i try to load configs

**Comment by martinjanas** [comment]
Not enough information for me to debug this, send your config.

**Comment by martinjanas** [comment]
@FriXeee

**Comment by FriXeee** [comment]
[config 2 new.zip](https://github.com/martinjanas/Sensum/files/7741910/config.2.new.zip)

**Comment by FriXeee** [comment]
sry for the wait
