### ISSUE TITLE
Skins not loaded (Skin Changer)

### ISSUE THREAD

**Issue by victorTrofelli** [martinjanas/Sensum#26]
The skin changer is not loading all skins properly, especially knives and gloves, always with the skins bug.
Please Help!
https://imgur.com/a/2EWRfM5

but the guns are working perfectly, only the knives and gloves have their bugged skins

**Comment by martinjanas** [comment]
-disable_d3d9ex into launch options.

**Comment by victorTrofelli** [comment]
> -disable_d3d9exex nas opções de inicialização.

I didn't understand, what would it be for me to do
