### ISSUE TITLE
Can't compile.

### ISSUE THREAD

**Issue by 3L337-n2** [martinjanas/Sensum#29]
Too many error after ur latest update. Such as value_sdk\interfaces\CClientState.h has some unicode that cause a error in my compiler(vs2019). I'm a noob for this so i don't know how to fix it.

**Comment by NNiX1** [comment]
make a screenshot im using too vs2019 and no problem already played mm with it

**Comment by ElectfriedTheGod** [comment]
![devenv_T2rFrRYV4o](https://user-images.githubusercontent.com/37424196/67586815-be40d200-f70f-11e9-9b9c-2abb51a4a876.png)

**Comment by 3L337-n2** [comment]
I think the problem should be the character encoding. I reaffirm again i'm noob of this. And I'm using big5 encoding . So, what should i change the encode to? Utf-8 or what? My computer is shutdown now. Hope somebody can answer me and I can use it tomorrow.

**Comment by NNiX1** [comment]
so i re-downloaded to check if there is something ... the only error is experimental  just search for experimental/filesystem and change it to filesystem  its 2 times there 
#include <experimental/filesystem>
to
#include <filesystem>

namespace fs = std::experimental::filesystem;
change it to 
namespace fs = std::filesystem;

should fix it

**Comment by 3L337-n2** [comment]
![84119](https://user-images.githubusercontent.com/53847134/67617826-b1100a00-f819-11e9-95c8-1b39a4aae5a3.jpg)
I doesn't touch any file of the project. Just compile....

**Comment by 3L337-n2** [comment]
@NNiX1 What character encoding you using?

**Comment by NNiX1** [comment]
default what was there uni ... did you removed experimental?

**Comment by 3L337-n2** [comment]
Nope....I'm not really understand how to remove it. @NNiX1

**Comment by NNiX1** [comment]
open project press ctrl + type experimental/filesystem hit enter  it will show you #include <experimental/filesystem> just remove experimental and / so it will look like this #include <filesystem>  row under this is namespace fs = std::experimental::filesystem; just remove experimental:: so it will look like this namespace fs = std::filesystem; then search again for experimental/filesystem  and do it again  done u can build it without problem

**Comment by 3L337-n2** [comment]
I reopen all the files and save as utf8 then only have 3 error...
![84119](https://user-images.githubusercontent.com/53847134/67618274-bb350700-f81f-11e9-83c8-782325a3985a.jpg)

**Comment by 3L337-n2** [comment]
Ok i try it

**Comment by 3L337-n2** [comment]
@NNiX1 press crtl + what?

**Comment by NNiX1** [comment]
ctrl + f sorry :D

**Comment by NNiX1** [comment]
and change it back to uni :D

**Comment by 3L337-n2** [comment]
Thx bro now it works normally. 
The dll is building \:)

**Comment by NNiX1** [comment]
told you :)  have fun !
