### ISSUE TITLE
new knife into old Original sensum source

### ISSUE THREAD

**Issue by stvnkng** [martinjanas/Sensum#31]
how to add new knife 20year csgo case in the old source thanks

**Comment by martinjanas** [comment]
https://github.com/martinjanas/Sensum/blob/master/src/features/skins.cpp#L64
https://github.com/martinjanas/Sensum/blob/master/src/features/skins.cpp#L35
https://github.com/martinjanas/Sensum/blob/master/src/valve_sdk/misc/Enums.hpp#L694#L695
https://github.com/martinjanas/Sensum/blob/master/src/hooks/sequence.cpp#L119#L132

**Comment by stvnkng** [comment]
> 
> 
> https://github.com/martinjanas/Sensum/blob/master/src/features/skins.cpp#L64
> https://github.com/martinjanas/Sensum/blob/master/src/features/skins.cpp#L35
> https://github.com/martinjanas/Sensum/blob/master/src/valve_sdk/misc/Enums.hpp#L694#L695
> https://github.com/martinjanas/Sensum/blob/master/src/hooks/sequence.cpp#L119#L132

Error	C2065	'WEAPON_KNIFE_CSS': undeclared identifier	Sensum	
http://prntscr.com/poooh2 any help plz?

**Comment by stvnkng** [comment]
WEAPON_KNIFE_CSS = 503, How to get this works? Enump.hpp

**Comment by stvnkng** [comment]
Hi, when i pressed F to spec the knife animation is bugy and dont show how to fix? thanks

**Comment by stvnkng** [comment]
https://youtu.be/G9he3KIWSpc

**Comment by trollman4444** [comment]
Lol what a retarded person. Ur lazy af. Just read void.to ffs

**Comment by trollman4444** [comment]
Just open skins.cpp, that's my hint u lazy person
