### ISSUE TITLE
can you fix <experimental/filesystem>

### ISSUE THREAD

**Issue by rayomi** [martinjanas/Sensum#33]
since the new update on visual studio 2019 they have removed <experimental/filesystem> function which runs into problems when compiling as i needed to remove the 'config' system which includes save, load and remove config.

**Comment by martinjanas** [comment]
open project press ctrl + type experimental/filesystem hit enter it will show you #include <experimental/filesystem> just remove experimental and / so it will look like this #include row under this is namespace fs = std::experimental::filesystem; just remove experimental:: so it will look like this namespace fs = std::filesystem; then search again for experimental/filesystem and do it again done u can build it without problem
