### ISSUE TITLE
VAC Error in Casual/DM.

### ISSUE THREAD

**Issue by Lochy59** [martinjanas/Sensum#34]
I remember that some cheats used to have a feature that you'd turn on if you wanted to go obvious in Casual/DM. Does this cheat have that feature, or am I doing something wrong?

**Comment by OTGCable** [comment]
You talking about rage? If you're looking for rage settings you're in the wrong place. Or you could paste the rage settings yourself. Up to you. Alternatively you could turn the aimbot fov all the way up and turn the smoothing down but you're bound to get overwatched/VAC'd eventually.

**Comment by Lochy59** [comment]
Nope. I just keep getting getting VAC errors in DM even when im only using visuals for example.

**Comment by martinjanas** [comment]
You got vac error because you probably had anti aim on, you can use anti aim only on mm,wingman, scrim & dangerzone.
