### ISSUE TITLE
Visual Glitch 

### ISSUE THREAD

**Issue by Norshgard** [martinjanas/Sensum#35]
I've been using this cheat (updated version) for quite a few days and it had been fine until now where this weird visual glitch appears out of nowhere. Before encountering this, I was just configuring the cheat. However when I launched the game and injected the cheat on the same very day, this visual glitch appeared. On that note, I did not use any other injector, so I assume there's something wrong with the cheat itself. Furthermore, the cheat works in local server(with this visual glitch) but crashes in multiplayer. Even when I tried to inject the cheat after loading into MMR, the same visual glitch will appear.
![image](https://user-images.githubusercontent.com/57094010/67672396-ccfae380-f9b2-11e9-87c4-a0552eeff9f6.png)

**Comment by martinjanas** [comment]
Increase debug fov in misc.

**Comment by Norshgard** [comment]
Oh thanks m8
