### ISSUE TITLE
New Knife Animation Bug

### ISSUE THREAD

**Issue by chuckmorris420** [martinjanas/Sensum#36]
Getting this animation bug with the "Classic Knife".

![classic knife bug](https://user-images.githubusercontent.com/33428878/67689984-0d973480-f994-11e9-9272-29ed50c4a9ec.PNG)

Only happens upon weapon inspection and not 100% of the time, this leads me to believe that this Knife Model has 2 inspection animations like the Deagle or Flip knife for example. I reckon one of the two animations for this knife is bugged. Not a major gameplay effecting issue but would be nice to be able to flex the new knife in footage ect. 
Also while on the topic of Knives, would it be possible to see you add the ability to have the vanilla model of a knife with no skin?
Hope this helps, Cheers for your work,
-)(-.

**Comment by liljekvist** [comment]
I have the same issue as above. As he said not anything gamebreaking but still kinda pisses me off.

**Comment by martinjanas** [comment]
I know about this, I cant do anything, we will need to wait to somebody post a fix, the anim fix was taken from nSkinz source.

**Comment by chuckmorris420** [comment]
Understood. Cheers for the reply. As for the vanilla skin on knife models, is that something you could see yourself adding in the future?

**Comment by martinjanas** [comment]
> Understood. Cheers for the reply. As for the vanilla skin on knife models, is that something you could see yourself adding in the future?

Added Vanilla skins, download newest game-items.json.
