### ISSUE TITLE
cs crashes when joining second match

### ISSUE THREAD

**Issue by depijs** [martinjanas/Sensum#37]
why does cs crashes after one game? i played 1 mm , and next time i join it just crashes the game.

**Comment by martinjanas** [comment]
Not sure, I will have to debug this.

**Comment by NNiX1** [comment]
atleast for me it crashes only if you start searching for a game and then go alt-tab without this not crashing on my end and its most likely auto-accept feature this happening in lots of pastes never debugged it

**Comment by depijs** [comment]
is crashing bug fixed

**Comment by martinjanas** [comment]
I didnt debug yet.

**Comment by martinjanas** [comment]
I fixed the crash when loading second match, did you noticed any more crashes?
