### ISSUE TITLE
Check your legit desync

### ISSUE THREAD

**Issue by atheleon** [martinjanas/Sensum#38]
Did some testing and was curious- please check your desync so that it is "proper"

https://youtu.be/VNWGWR1pLBM

**Comment by martinjanas** [comment]
I tried to replicate the position as closest as possible.

https://imgur.com/a/HVKMDbc

This is how it looks on my side, are you using latest Sensum?

**Comment by atheleon** [comment]
"fake angle" still doesn't do the respective 60 degree opposite to the real while using the "static" desync variant.

**Comment by atheleon** [comment]
Here is another video, your real head changing sides is not the option. The fake changing in response to it is. Here is some math.

Lets take your real angle (r) as -30 for Flip 1, so your fake angle (f) is 28-30 the distance between the two is your max_desync or roughly 60 degrees. We will be comparing math between each scenario as if you have used the flip key for desync.

Flip 1:
r(-30) and f(30)
this difference is roughly 60 degrees

Flip 2 (since your fake isn't reset, at least from what I have seen, this could be an issue with desync or thirdperson visual error):
r(30) and f(30-60) 
this difference is only 0 or 30 degrees

Video Here: https://youtu.be/4AkVh1YrEYY

**Comment by martinjanas** [comment]
1. New anti aim is in create move hook, you opened old anti aim cpp.

Looks like its the chams problem, its not 100% accurate.

Take a look: https://youtu.be/Jf0vPItfxyw

This is chams code:

```
void DesyncChams()
	{
		if (!g::engine_client->IsInGame() || !g::engine_client->IsConnected())
			return;

		if (interfaces::local_player->m_bGunGameImmunity() || interfaces::local_player->m_fFlags() & FL_FROZEN)
			return;

		Vector OrigAng;
		IMaterial* Dagtag = g::mat_system->FindMaterial("models/inventory_items/dogtags/dogtags_outline", "Other textures");
		IMaterial* flat = g::mat_system->FindMaterial("debug/debugdrawflat", "Other textures");
		IMaterial* regular = g::mat_system->FindMaterial("simple_regular", TEXTURE_GROUP_MODEL);
		IMaterial* Metallic = g::mat_system->FindMaterial("simple_reflective", TEXTURE_GROUP_MODEL);
		OrigAng = g::local_player->GetAbsAngles2();
		g::local_player->SetAngle2(Vector(0, g::local_player->GetPlayerAnimState2()->m_flEyeYaw, 0)); //around 90% accurate
		if (g::Input->m_fCameraInThirdPerson)
		{
			g::mdl_render->ForcedMaterialOverride(Metallic);
			g::render_view->SetColorModulation(1.0f, 1.0f, 1.0f);
		}
		g::local_player->GetClientRenderable()->DrawModel(0x1, 255);
		g::local_player->SetAngle2(OrigAng);
	}
```

**Comment by atheleon** [comment]
We should work on this together... Might be a nice thing- will work towards an autowall based legit desync.
