### ISSUE TITLE
Lags 🤔

### ISSUE THREAD

**Issue by Sl4vP0weR** [martinjanas/Sensum#39]

**Comment by martinjanas** [comment]
Im not having any big fps drops. I run without injected cheat about 150-200 fps/depends on map

Injected I have around 140-170 fps/depends on map.

**Comment by Sl4vP0weR** [comment]
I have lags on inject and I dont know what I supposed to do :/

**Comment by Sl4vP0weR** [comment]
@martinjanas please help me
