### ISSUE TITLE
Backtrack isn't working for me.

### ISSUE THREAD

**Issue by chuckmorris420** [martinjanas/Sensum#42]
Just realised i cant backtrack anything in the "aim_botz" map while editing a config. I have a FOV, hitboxes, aimbot tab enabled and lag compensation is at max and i cant backtrack anyone.
Am i forgetting something or is the new backtrack bugged?

**Comment by depijs** [comment]
backtrack works fine for me.

**Comment by martinjanas** [comment]
You have to update your config and then it will start working.
