### ISSUE TITLE
legit aa  on high ping

### ISSUE THREAD

**Issue by stvnkng** [martinjanas/Sensum#44]
cant walk properly if ping  is 200 any  fix?

**Comment by martinjanas** [comment]
I know about this issue, but I havent found a fix for now.

**Comment by atheleon** [comment]
working on a desync rework- but really? 200 ping?

**Comment by martinjanas** [comment]
I fixed it.

Go into create move.cpp

and change this:

float fl_latency = g::engine_client->GetNetChannelInfo()->GetLatency(FLOW_OUTGOING);

to this:

float fl_latency = g::engine_client->GetNetChannelInfo()->GetLatency(FLOW_INCOMING);
