### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by depijs** [martinjanas/Sensum#50]
feature requests here ^_^

**Comment by martinjanas** [comment]
You can use github

**Comment by depijs** [comment]
-add blockbot
- improve legit aa
these are my suggestions

**Comment by martinjanas** [comment]
What should be improved on aa?

**Comment by depijs** [comment]
idk, i just have used aimware legit aa and it was good,lot of shit cheats shot my aa, with sensum i just get tapped

**Comment by atheleon** [comment]
> idk, i just have used aimware legit aa and it was good,lot of shit cheats shot my aa, with sensum i just get tapped

learn how to use it properly, only issues with it are that viewing angles in thirdperson are not accurate

**Comment by martinjanas** [comment]
The legit aa is fine, also as Atheleon said you need to learn how to use it.

Ofcource you will get tapped by p2c.

Look here:
https://youtu.be/Xm2FSq1kPnY

**Comment by notyourneighbour** [comment]
Yo blockbot would be an awesome idea. Like for trolling n stuff

**Comment by Ciprianbeleaua** [comment]
can you also add edgejump please? it would be a nice addition

**Comment by atheleon** [comment]
All of these features can be added by you, the user!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by martinjanas** [comment]
I will add these features once i figure out how to make them.I will prob look at some public sources to get a inspiration.

**Comment by p-lok** [comment]
Got edge jump, was pretty easy to make. I had some problems initially because the pre and post enginepred had heaps of functions in between when they were being called in createmove, so it played with my flags at the given time, so I couldn't jump and stuff. Also the 2 lines in the image below are resetting the engine prediction, might want to comment them out like I did (line number might be different idek)
![image](https://user-images.githubusercontent.com/55611327/68292155-5f9c3080-00df-11ea-9bfb-3dd5f227f044.png)

**Comment by martinjanas** [comment]
> Got edge jump, was pretty easy to make. I had some problems initially because the pre and post enginepred had heaps of functions in between when they were being called in createmove, so it played with my flags at the given time, so I couldn't jump and stuff. Also the 2 lines in the image below are resetting the engine prediction, might want to comment them out like I did (line number might be different idek)
> ![image](https://user-images.githubusercontent.com/55611327/68292155-5f9c3080-00df-11ea-9bfb-3dd5f227f044.png)



Yeah, got it working as well. It wasnt jumping until I removed the lines in engine prediction.

**Comment by NNiX1** [comment]
when we are in grief features radio spam drives ppl crazy with a block bot its and ultimate weapon :D

**Comment by depijs** [comment]
Add a feature where you can see who presses F1/F2 in votes. (have used this on other cheats with lua help)

**Comment by You02** [comment]
please change the json file to a kitparser or something please im begging you lmao

**Comment by stvnkng** [comment]
fake duck  like gamesense? they cant see your head but u can shoot them , e.g near shadow mirage A entrance

**Comment by stvnkng** [comment]
enemy fake angle chams?

**Comment by martinjanas** [comment]
> enemy fake angle chams?

Not possible, I have no way to get enemy entity's fake angle.

**Comment by bigfknballer** [comment]
hey, any chance you could show me how i can change the code for clantag so it goes back to 0? instead of resetting when its finished or whatever. idk how to explain it better, but i hope you understand. thank you very much :) onliner#1362 on discord if anyone would be kind enough to show me

**Comment by martinjanas** [comment]
> hey, any chance you could show me how i can change the code for clantag so it goes back to 0? instead of resetting when its finished or whatever. idk how to explain it better, but i hope you understand. thank you very much :) onliner#1362 on discord if anyone would be kind enough to show me

You mean like it will go from first letter to last letter and then from last letter to first letter?

**Comment by bigfknballer** [comment]
> > hey, any chance you could show me how i can change the code for clantag so it goes back to 0? instead of resetting when its finished or whatever. idk how to explain it better, but i hope you understand. thank you very much :) onliner#1362 on discord if anyone would be kind enough to show me
> 
> You mean like it will go from first letter to last letter and then from last letter to first letter?

exactly! im pretty new to all of this so i would appreciate if you could help me

**Comment by bigfknballer** [comment]
hey, got a issue with the new updated version. whenever i duck my character stays upright as if i never ducked and my weapon disapeared etc. is this a normal bug or?

**Comment by stvnkng** [comment]
how to get gamesense tag?

**Comment by atheleon** [comment]
> hey, got a issue with the new updated version. whenever i duck my character stays upright as if i never ducked and my weapon disapeared etc. is this a normal bug or?

Remove the fake duck function.

**Comment by p-lok** [comment]
> Remove the fake duck function.
Duck works fine even with fake duck function for me?

> hey, got a issue with the new updated version. whenever i duck my character stays upright as if i never ducked and my weapon disapeared etc. is this a normal bug or?

did you change anything to do with fakeduck/do you have it on? the point of fake duck is to be upright but on other peoples' screens you're ducking. Maybe try turning off the setting.

**Comment by stvnkng** [comment]
> 
> 
> > Remove the fake duck function.
> 
> Duck works fine even with fake duck function for me?
> 
> > hey, got a issue with the new updated version. whenever i duck my character stays upright as if i never ducked and my weapon disapeared etc. is this a normal bug or?
> 
> did you change anything to do with fakeduck/do you have it on? the point of fake duck is to be upright but on other peoples' screens you're ducking. Maybe try turning off the setting.
> 
> Ontopic: old gloves and sounds would be pretty cool if you can figure out how to hook findmdl properly, mines pretty ghetto rn and doesnt work lmao

does enmy see u fake ducking or see u upright when u fake ducking?

**Comment by kredzor** [comment]
font and font size changer, maybe like in osiris

**Comment by p-lok** [comment]
> does enmy see u fake ducking or see u upright when u fake ducking?

they see you ducking iirc

**Comment by BHOPERGUY** [comment]
-add viewmodel offsets plz

**Comment by kredzor** [comment]
Add override resolver
Optimize autowall, when i look thru the 2-3 walls, i got fps drop.

**Comment by Falmze** [comment]
fix legit aa 
fix real angle chams
make better RCS
that's all :)

**Comment by Falmze** [comment]
fix sensum when I join mm with it my whole game glitches and i cant see anything

**Comment by martinjanas** [comment]
> add Lua
> fix real angle chams
> make better RCS
> that's all :)

There's no need to make better rcs, its already perfect.Just drag mouse a down little and its perfect.
I made real angle chams 90% accurate, I cant make them more accurate, thats all I can do for them.

**Comment by Falmze** [comment]
> > add Lua
> > fix real angle chams
> > make better RCS
> > that's all :)
> 
> There's no need to make better rcs, its already perfect.Just drag mouse a down little and its perfect.
> I made real angle chams 90% accurate, I cant make them more accurate, thats all I can do for them.

well then can you add lua in the next update

**Comment by Falmze** [comment]
update sensum please

**Comment by Falmze** [comment]
real angle chams are broken

**Comment by martinjanas** [comment]
> real angle chams are broken

Can you elaborate?

**Comment by Falmze** [comment]
when i put desync on i turn on visuals then i put on real angle chams they dont show

**Comment by martinjanas** [comment]
> I put desync on, I turn on visuals then I put on real angle chams but they don't show for some reason

You cant see it because of this:

![image](https://user-images.githubusercontent.com/44605473/70847091-72cdb900-1e60-11ea-81e3-8654529e9fc7.png)
![image](https://user-images.githubusercontent.com/44605473/70847099-824d0200-1e60-11ea-9efb-1b4903c7953c.png)
![image](https://user-images.githubusercontent.com/44605473/70847104-8b3dd380-1e60-11ea-9556-f3eab8fbab80.png)

**Comment by Falmze** [comment]
> > I put desync on, I turn on visuals then I put on real angle chams but they don't show for some reason
> 
> You cant see it because of this:
> 
> ![image](https://user-images.githubusercontent.com/44605473/70847091-72cdb900-1e60-11ea-81e3-8654529e9fc7.png)
> ![image](https://user-images.githubusercontent.com/44605473/70847099-824d0200-1e60-11ea-9efb-1b4903c7953c.png)
> ![image](https://user-images.githubusercontent.com/44605473/70847104-8b3dd380-1e60-11ea-9556-f3eab8fbab80.png)

Then what should i do to fix it?

**Comment by Falmze** [comment]
Build 15.0.0

Real Angle Chams Are not Working
Thirdperson is glitched and stutters and glitches my character when I'm using it
15/12/2019

**Comment by martinjanas** [comment]
Did you test real chams in mm gamemode? ex: wingman, 5v5, 5v5 unranked, dangerzone? 

Because anti aim is disabled in non-mm gamemodes.

**Comment by Falmze** [comment]
> Did you test real chams in mm gamemode? ex: wingman, 5v5, 5v5 unranked, dangerzone?
> 
> Because anti aim is disabled in non-mm gamemodes.

ok i will try it and report back to you

**Comment by Falmze** [comment]
I have tried it in mm like you said third person issues were solved but real angle chams still don't work.
![2](https://user-images.githubusercontent.com/58751308/70858450-662b8c80-1f56-11ea-8b45-f1256939cd02.PNG)
![2](https://user-images.githubusercontent.com/58751308/70858452-675cb980-1f56-11ea-9a7d-b4f5c01a05ec.PNG)

**Comment by martinjanas** [comment]
And do you have anti aim even enabled?

**Comment by martinjanas** [comment]
As you can see its working fine:

(Its working on aim_botz, because I changed game_mode to 1)

https://media.discordapp.net/attachments/557273105232297995/655523264814383105/unknown.png?width=1443&height=570

**Comment by Falmze** [comment]
yes i had it enabled

**Comment by Falmze** [comment]
build 1.5.0
- in casual the aimbot settings reset every like 5 minutes
16/12/2019

**Comment by Falmze** [comment]
add hvh features :P

**Comment by martinjanas** [comment]
> add hvh features :P
No,
literally use some good hvh cheat, this is legit cheat...

**Comment by Falmze** [comment]
ok so umm aimbot reset's after a few minutes and trigger also doesn't work.

**Comment by xBlackElite** [comment]
> ok so umm aimbot reset's after a few minutes and trigger also doesn't work.

Thats a u issue

**Comment by xBlackElite** [comment]
Add fake prime, fix enemy chams.

**Comment by martinjanas** [comment]
> Add fake prime, fix enemy chams.

I wont add fake prime, its patching bytes in .text section and patching bytes in .text section is causing vac bans.

Next time you could elaborate what you mean by: fix enemy chams.

**Comment by xBlackElite** [comment]
> > Add fake prime, fix enemy chams.
> 
> I wont add fake prime, its patching bytes in .text section and patching bytes in .text section is causing vac bans.
> 
> Next time you could elaborate what you mean by: fix enemy chams.

Sometimes enemy chams are bugged like the legs arent rendering its weird.

**Comment by xBlackElite** [comment]
- Dark Menu doesnt load on config load.
- Try add bigger backtrack [400ms].
- Try add backtrack chams. That would be amazing feature.

**Comment by p1pS** [comment]
Try adding an inventory/medal/profile changer. I got everything implemented, just my game crashes when I hook try to send_message and retrieve_message. Can't debug it because protobuf is cancer to debug, i.e:
![image](https://user-images.githubusercontent.com/58621645/71501166-db834f80-28bc-11ea-9307-2388134ca4c2.png)

**Comment by NekoRem** [comment]
inventory, medal and profile changers are next to useless and can cause cheat stability to drop if made poorly. A simple skin changer should suffice as its not as if other people can see the changes or would make a difference.

**Comment by OTGCable** [comment]
> * Dark Menu doesnt load on config load.
> * Try add bigger backtrack [400ms].
> * Try add backtrack chams. That would be amazing feature.

Long backtrack was causing massive FPS drops back when it was added iirc. 
Also, it's a legit cheat, idk why on earth you'd want 400 millisecond backtrack, that's absurd.

**Comment by linkupbiz** [comment]
This cheat comes very close to as good as a legit p2c, except it is free, I feel like certain things should be re organized, such as the aimbot tab, if you would like I could make an edited images with with annotations of what should be changed in each tab.

**Comment by martinjanas** [comment]
> This cheat comes very close to as good as a legit p2c, except it is free, I feel like certain things should be re organized, such as the aimbot tab, if you would like I could make an edited images with with annotations of what should be changed in each tab.

Yeah, sure.Why not.

**Comment by atheleon** [comment]
> This cheat comes very close to as good as a legit p2c, except it is free, I feel like certain things should be re organized, such as the aimbot tab, if you would like I could make an edited images with with annotations of what should be changed in each tab.

It’s open source for a reason. If you don’t like the menu, change it.

**Comment by NekoRem** [comment]
> > * Try add bigger backtrack [400ms].
> 
> Long backtrack was causing massive FPS drops back when it was added iirc.
> Also, it's a legit cheat, idk why on earth you'd want 400 millisecond backtrack, that's absurd.

you can get up to 600ms backtrack so 400ms isn't enough.

**Comment by Repisz** [comment]
i inject the cheat and i get fps drop 300 to 60-70

**Comment by Luizfps14** [comment]
what about music kit changer?

**Comment by OTGCable** [comment]
> > > * Try add bigger backtrack [400ms].
> > 
> > 
> > Long backtrack was causing massive FPS drops back when it was added iirc.
> > Also, it's a legit cheat, idk why on earth you'd want 400 millisecond backtrack, that's absurd.
> 
> you can get up to 600ms backtrack so 400ms isn't enough.

you're missing the point. it's not a matter of whether it's enough or not, or even if it's possible for that matter, it's a matter of whether or not it'll be 
A) Appropriate for a **_LEGIT_** cheat or
B) Stable enough to not cause a massive FPS dump when enabled.

**Comment by depijs** [comment]
why was this closed 🤔
