### ISSUE TITLE
Massive bug 

### ISSUE THREAD

**Issue by NNiX1** [martinjanas/Sensum#51]
so yesterday i build cheat again and was curious how u progressing with it and saw lots of improvments (good job)  but i played a deathmatch with aimbot/chams/fast stop/and changed knife on and match was fine but then after match finished i started another DM and thats was when shit happens  went from 250 to 16 fps and when i opened console it went crazy so crazy that i cant even read a single line of whats going on  but had no time to debug it  is this a common issue ? or do you know whats causing it? if not i will try to re-do what i did in debug and i will post it here

**Comment by martinjanas** [comment]
Its probably caused by IncrementReferenceCount in chams.cpp, with without that I found out that it can crash.

**Comment by martinjanas** [comment]
Im gonna remove IncrementReferenceCount and test if it will crash.

**Comment by NNiX1** [comment]
so i turned on game and got straight back to 50ish fps range caused by skinchanger 
this was in console in csgo : 
Failed to set custom material for 'knife_m9_bay', no matching material name found on model models/weapons/w_knife_default_t.mdl

but today console is relativly calm it will fail to load m9 skin but in console is just 5 lines of it but yesterday it was unreadable

**Comment by martinjanas** [comment]
So I removed the "IncrementReferenceCount" and didnt crash once, I will update github in a hour max.

**Comment by NNiX1** [comment]
okay will check it when its here tryied to debug my yesterday thing played 5 DM's but its not happening rn so will see if  i encounter it with IncrementReferenceCount :)
