### ISSUE TITLE
Crashing on Inject

### ISSUE THREAD

**Issue by notyourneighbour** [martinjanas/Sensum#53]
Well i injected yesterday it worked fine but today csgo got an update i think and its crashing all the time. I respect you and your hard work for doing this for people you dont even know :D. Keep up the good work my brother

**Comment by juauzynhu** [comment]
Working fine here

**Comment by martinjanas** [comment]
I dont crash on inject.

**Comment by NNiX1** [comment]
yeah i now did lvl 2 and didnt had any problem with injecting / fps ( so last fix worked well :) )
