### ISSUE TITLE
Triggerbot isn't as expected

### ISSUE THREAD

**Issue by juauzynhu** [martinjanas/Sensum#54]
Triggerbot isn't shooting exactly at target body, but seems like it shoots at a boundary box around target.

Using trigger with AWP is like a prefire.

**Comment by martinjanas** [comment]
Thats probably because its magnet triggerbot.

**Comment by atheleon** [comment]
>Triggerbot isn't shooting exactly at target body, but seems like it shoots at a boundary box around target. ...

@juauzynhu adjust your hitchance and minimum damage settings. This will fix the “prefire” issues. /close

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by juauzynhu** [comment]
Hitchance is already at 100%. I'll take a look at minimum damage settings.

**Comment by stvnkng** [comment]
> 
> 
> > Triggerbot isn't shooting exactly at target body, but seems like it shoots at a boundary box around target. ...
> 
> @juauzynhu adjust your hitchance and minimum damage settings. This will fix the “prefire” issues. /close
> 
> Sent with [GitHawk](http://githawk.com)

what hitchance and mini damage do u use for deagle and awp?

**Comment by juauzynhu** [comment]
> > > Triggerbot isn't shooting exactly at target body, but seems like it shoots at a boundary box around target. ...
> > 
> > 
> > @juauzynhu adjust your hitchance and minimum damage settings. This will fix the “prefire” issues. /close
> > Sent with [GitHawk](http://githawk.com)
> 
> what hitchance and mini damage do u use for deagle and awp?

Like printscreen, I use same for all.
