### ISSUE TITLE
Mouse not showing in menu? 

### ISSUE THREAD

**Issue by NNiX1** [martinjanas/Sensum#55]
Hey do anyone else having problem with mouse in main menu not showing up? or its just me?

**Comment by martinjanas** [comment]
Press escape or console key once you close menu, this rarely happens.

**Comment by NNiX1** [comment]
for me mouse is not showing up every time i launch a game but i visited osiris and have it fixed .. pull?

**Comment by martinjanas** [comment]
Sure, you can.
