### ISSUE TITLE
bunnyhop doesnt work with engine prediction

### ISSUE THREAD

**Issue by depijs** [martinjanas/Sensum#58]
bunnyhop doesnt work if engine prediction is enabled.
also real angles didnt show up too

**Comment by martinjanas** [comment]
1. Real angles only show up when you are playing mm, wingman, scrim or dangerzone, because desyncAA is disabled outside mm and if you are playing on Valve dedicated servers.

2. Bunnyhop and other related movement stuff is fixed now, thanks.
