### ISSUE TITLE
i have to delete memesense to inject the cheat without crashing 

### ISSUE THREAD

**Issue by joemays1** [martinjanas/Sensum#59]
that the title says

**Comment by martinjanas** [comment]
I experienced something similar when I deleted statrack file, I had to open the statrack file in notepad, ctrl + a everything and delete all inside.

Try that. If you have rar file, or any other file type in "settings" folder delete it! I was once sending configs to my friend and I had rar in settings folder and I was crashing.

**Comment by joemays1** [comment]
> I experienced something similar when I deleted statrack file, I had to open the statrack file in notepad, ctrl + a everything and delete all inside.
> 
> Try that. If you have rar file, or any other file type in "settings" folder delete it! I was once sending configs to my friend and I had rar in settings folder and I was crashing.

that didn't work  https://prnt.sc/pv0g30 it crashes as soon as inject

**Comment by joemays1** [comment]
i fixed it was a old config but can i get your config
