### ISSUE TITLE
RCS Crosshair Not Displaying

### ISSUE THREAD

**Issue by chuckmorris420** [martinjanas/Sensum#60]
I cannot get the RCS Crosshair to display, neither circle or cross works. Noticed the attempts on making the dynamic FOV being displayed aswell, good luck with it.

**Comment by martinjanas** [comment]
![image](https://user-images.githubusercontent.com/44605473/68546571-03375a80-03d8-11ea-9d17-341728bee85b.png)

**Comment by chuckmorris420** [comment]
Ah my bad I didn't even know you had this on UC, was just following the Git. Cheers for the reply.
