### ISSUE TITLE
silence aim working?

### ISSUE THREAD

**Issue by stvnkng** [martinjanas/Sensum#61]
is silence aim for deagle working ? i use fov1 but the dont hit at one shot
fake lag , what the recommended tick u guys recommend for global mm hvh without looking laggy on ow so Overwatcher dont see the fake lagging. what the diff betweeen adatative , when picking etc? thanks

**Comment by martinjanas** [comment]
Silent aim is working for deagle.

**Comment by stvnkng** [comment]
> 
> 
> Silent aim is working for deagle.

should i enable aimbot also?

**Comment by martinjanas** [comment]
yes
