### ISSUE TITLE
Error when compiling 

### ISSUE THREAD

**Issue by Y3H801** [martinjanas/Sensum#62]
Severity	Code	Description	Project	File	Line	Suppression State	Suppression State
Error	C1189	#error:  The <experimental/filesystem> header providing std::experimental::filesystem is deprecated by Microsoft and will be REMOVED. It is superseded by the C++17 <filesystem> header providing std::filesystem. You can define _SILENCE_EXPERIMENTAL_FILESYSTEM_DEPRECATION_WARNING to acknowledge that you have received this warning. (compiling source file config.cpp)	Sensum	C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.23.28105\include\experimental\filesystem	26		

Unsure how to fix this...

**Comment by p-lok** [comment]
Go to the file it says (config.cpp). Replace the experimental header with the non-experimental (from `<experimental/filesystem>` to `<filesystem>`). Replace the namespace definition (idek what to call it) (from `namespace fs = std::experimental::filesystem;` to `namespace fs = std::filesystem;`). You have to do the same thing in options.cpp.

**Comment by Y3H801** [comment]
This worked perfectly, thanks for your help!
