### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by shroomcave** [martinjanas/Sensum#67]
When I load into any game I get a dialogue box saying something related to the following " imgui.cpp 5235 p_backup == current && ? push style colour/popstylecolour mismatch " 

It gives me a few options, Abort, Retry, or Ignore. No matter what I choose it either crashes or spams the box (retrying). I tried fixing it but I have no idea what is going on or how to fix it, please help. Thank you.

**Comment by martinjanas** [comment]
thats because of imgui, cant do anything.

**Comment by NNiX1** [comment]
this happens only in debug mode so if u wanna just play change debug --> release

**Comment by shroomcave** [comment]
This fixed the crashing, on top of issues I was having because of using debug, thank you.
