### ISSUE TITLE
New Skins

### ISSUE THREAD

**Issue by chuckmorris420** [martinjanas/Sensum#68]
Not really a gameplay effecting issue, I don't know how to get the model tag and name for the format in "game-items.json", I can get the ID's from CSGOStash.com if that is all that is needed. I could even volunteer to help with it if pointed in the right direction just I am busy with college so it wont be fast.

Cheers for your time.

https://csgostash.com/case/277/Shattered-Web-Case
https://csgostash.com/collection/The+Canals+Collection
https://csgostash.com/collection/The+Norse+Collection
https://csgostash.com/collection/The+St.+Marc+Collection

**Comment by martinjanas** [comment]
New skins should be available today, but more likely tommorow.

**Comment by chuckmorris420** [comment]
Much love martinjanas, 
Appreciate the hard work.
