### ISSUE TITLE
EndScene hook?

### ISSUE THREAD

**Issue by deprale** [martinjanas/Sensum#7]
How can I make everything OBS-PROOF by rendering in endscene hook instead of present?

Also quite funny that visual studio literally hangs when compiling this lol.

**Comment by tirziz** [comment]
> How can I make everything OBS-PROOF by rendering in endscene hook instead of present?
> 
> Also quite funny that visual studio literally hangs when compiling this lol.

I've just seen your Issue from Osiris and now here xD

**Comment by martinjanas** [comment]
I have been trying to make the cheat obs proof,but after I did everything that was in UC topic when I started obs menu was invisible on my screen and visible on obs screen.
