### ISSUE TITLE
Skin Changer

### ISSUE THREAD

**Issue by victorTrofelli** [martinjanas/Sensum#70]
Why is the skin changer showing up all game skins for the same weapon?

![image](https://user-images.githubusercontent.com/49568664/69278688-95eaad00-0bc1-11ea-8663-be654c3feffd.png)

**Comment by OTGCable** [comment]
eh, i had the same complaint at first, but it's not as bad as i'd originally thought. for instance, if you want the asiimov all of the asiimov skins are labelled by weapon so it's not too bad imho.
