### ISSUE TITLE
Update patterns.h to prevent crashes on deathmatch. Here is ready code to replace with.

### ISSUE THREAD

**Issue by Kenix97** [martinjanas/Sensum#75]
#define CLIENT_STATE			 xorstr_("engine.dll"), xorstr_("A1 ? ? ? ? 33 D2 6A 00 6A 00 33 C9 89 B0")
#define GAME_RULES_PROXY		 xorstr_("client.dll"), xorstr_("A1 ? ? ? ? 85 C0 0F 84 ? ? ? ? 80 B8 ? ? ? ? ? 74 7A")

**Comment by martinjanas** [comment]
Thanks, pushing update now.
