### ISSUE TITLE
LNK2001 error

### ISSUE THREAD

**Issue by Nikutsuke** [martinjanas/Sensum#77]
Hello i got everything to work added junk code and tried to compile it but get this error
"Severity	Code	Description	Project	File	Line	Suppression State	Suppression State
Error	LNK2001	unresolved external symbol "public: static class vfunc_hook hooks::mdlrender::hook" (?hook@mdlrender@hooks@@2Vvfunc_hook@@A)	Sensum	C:\Users\mateusz\Downloads\Sensum-master\Sensum-master\src\Chams.obj	1		"
anybody want to help me? dont close it please.

**Comment by gosha98** [comment]
ME TOO
