### ISSUE TITLE
Cannot build because of error c1189

### ISSUE THREAD

**Issue by sheeshbrobro** [martinjanas/Sensum#78]
Please help me with this issue , i've been trying to fix it for hours.

**Comment by gosha98** [comment]
did u get this error :
LNK2001	unresolved external symbol "public: static class vfunc_hook hooks::mdlrender::hook" (?hook@mdlrender@hooks@@2Vvfunc_hook@@A) ?

**Comment by afulsamet** [comment]
I think he's talking about this mistake. i get this error too.
![devenv_9YAh6SJLAn](https://user-images.githubusercontent.com/27636298/70230607-bf7f0900-1769-11ea-8418-8a477e10e87f.png)

**Comment by martinjanas** [comment]
Just read the damn error... Closed.
