### ISSUE TITLE
Template for making issues - README!

### ISSUE THREAD

**Issue by martinjanas** [martinjanas/Sensum#81]
### This document is the template for making issues, please copy this text below and paste it in your issue:

Sensum version: 
Problem description: how, when... (when its happening, etc...)

### Examples:

**#1:
Sensum version: 1.7.0
Problem description: Bhopping with awp is causing massive fps drops.**

**#2:
Sensum version: 1.12.10
Problem description: The cheat is crashing while loading to map.**

**Comment by Berxz** [comment]
when building sensum this error appeared:


1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include\experimental\filesystem(30,1): fatal error C1189: #error:  The <experimental/filesystem> header providing std::experimental::filesystem is deprecated by Microsoft and will be REMOVED. It is superseded by the C++17 <filesystem> header providing std::filesystem. You can define _SILENCE_EXPERIMENTAL_FILESYSTEM_DEPRECATION_WARNING to acknowledge that you have received this warning. (compiling source file config.cpp)
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include\experimental\filesystem(30,1): fatal error C1189: #error:  The <experimental/filesystem> header providing std::experimental::filesystem is deprecated by Microsoft and will be REMOVED. It is superseded by the C++17 <filesystem> header providing std::filesystem. You can define _SILENCE_EXPERIMENTAL_FILESYSTEM_DEPRECATION_WARNING to acknowledge that you have received this warning. (compiling source file options.cpp)

**Comment by swabbed** [comment]
Whenever i go to build my project of Sensum, it comes up with these two errors which in turn cause 88+ warnings.This has happened on the 26th and 24th. [https://i.imgur.com/yI2cKYa.png](url)

**Comment by Luizfps14** [comment]
Version:1..5.6
my skin changer isn't working,there is nothing in the skins and it doesn't appear even if i type the name of the skin or it seed,pls help

**Comment by AntonnMal** [comment]
Did you put game-items.json in memesense folder?

P.S. You shouldn't comment here, you should have created a new issue.

**Comment by Luizfps14** [comment]
yep,and sorry,idk how to use git bcz i'm new to it
