### ISSUE TITLE
Crashing when die and wit cfg when join

### ISSUE THREAD

**Issue by METIX75** [martinjanas/Sensum#85]
even with updated dll

141v and sdk 1.7

**Comment by martinjanas** [comment]
Build the cheat in debug, attach debugger to csgo, inject debug version of dll and play.Let it trigger on some breakpoint and then post screenshot.

**Comment by METIX75** [comment]
hiar https://prnt.sc/qcnjcx

**Comment by A0J3X** [comment]
same
volvo pls fix
