### ISSUE TITLE
Error messages when building project

### ISSUE THREAD

**Issue by swabbed** [martinjanas/Sensum#88]
Whenever i go to build my project of Sensum, it comes up with these two errors which in turn cause 88+ warnings.This has happened on the 26th and 24th. [https://i.imgur.com/yI2cKYa.png](url)

**Comment by Naqix** [comment]
he literally said 
Report bugs here: https://github.com/martinjanas/Sensum/issues

Dont post issues on Github about VS not compiling! Use Google and brain.

what do you do? You post issues bout vs not compiling
