### ISSUE TITLE
Errors when compiling project

### ISSUE THREAD

**Issue by swabbed** [martinjanas/Sensum#89]
Whenever i go to build my project of Sensum, it comes up with these two errors which in turn cause 88+ warnings.This has happened on the 26th and 24th. https://i.imgur.com/yI2cKYa.png

**Comment by p1pS** [comment]
Do what it says, you have 2 choices:
**1** (bad way). Define the silence thing:
`#define _SILENCE_FILESYSTEM_DEPRECATION_WARNING`
at the top of both files (config.cpp and options.cpp).
OR
**2** (the proper way). Change the `#include <experiemental/filesystem>` to `#include <filesystem>` and change the `std::experimental::filesystem` to `std::filesytem` in both files (config.cpp and options.cpp).
Should work.
