### ISSUE TITLE
FPS Drop/ Knifebot Issue

### ISSUE THREAD

**Issue by Exonip** [martinjanas/Sensum#91]
I just compiled from the source. But the Game drops A LOT a frames. Normaly I got about 120 FPS but when im injected I only got around 30 max. This only heppens with Sensum. If you want I can provide video footage/screenshare cuz it looks like I am not the only one having the problem. Aswell as the Knifebot is making the game lag as HELL. It realy is not playable anymore.

**Comment by Exonip** [comment]
I would be very happy about an answer, because I find the cheat very good and would like to use it.

**Comment by martinjanas** [comment]
A lot of ppl say the are dropping frames, but I dont drop a single frame when playing without cheats and when playing with Sensum. So I cant do much, because I dont experience this. Simply dont use knifebot if its laggy for you.

**Comment by Exonip** [comment]
If you want, I can show u what I did... I would realy like it if I could use the cheat... Could u send my a working dll? Maybe I failed to compile it correct

**Comment by martinjanas** [comment]
You can try to start the cheat with all disabled and then slowly start enabling features 1 by 1 and record that.

**Comment by Exonip** [comment]
With disabled u mean removed from from source?

**Comment by martinjanas** [comment]
all features disabled in the menu.

**Comment by Exonip** [comment]
Even is I disable all of them in the menu I still only got 30fps I just injected and my frames drop

**Comment by martinjanas** [comment]
Post screenshot of your video settings.

**Comment by Exonip** [comment]
wait a minute...

**Comment by Exonip** [comment]
*19 minutes sorry... https://www.youtube.com/watch?v=pNl4IYDZupQ

**Comment by martinjanas** [comment]
1st: build in release, not debug... Debug is eater of fps.

**Comment by Exonip** [comment]
Should I enable optimization?

**Comment by martinjanas** [comment]
Shouldnt matter, just dont build the cheat in debug version.

![image](https://user-images.githubusercontent.com/44605473/71536838-22506400-2914-11ea-8dfc-991107007285.png)

**Comment by Exonip** [comment]
I'm just completely retarded... Like that was the flaw...  i'll just send you 5 euro on paypal as compensation for my stupidity and the time u spend 4 this...

**Comment by martinjanas** [comment]
Thats ok, atleast Im glad you helped me figure out the fps drops ppl said they have. Thanks.
