### ISSUE TITLE
Crash on online match (not when playing with bots)

### ISSUE THREAD

**Issue by Exonip** [martinjanas/Sensum#93]
Yes, it's me again... This time I have the problem that my csgo crashes when I enter an online match. I have no problems with bots. I just compiled and injected the cheat in realease. I have tried it with several of them already, the injector is not the problem. Video: https://www.youtube.com/watch?v=gSY6N46yopQ
(Sorry, I'm not able to cut.)

**Comment by martinjanas** [comment]
Yeah, I have been trying to fix the crash with -98 nade on map load, map exit and death.

So disable -98 nade and post screenshot of your enabled features in misc.

**Comment by Exonip** [comment]
Thanks for your fast anwser again! Gonna try it

**Comment by Exonip** [comment]
Ok, works if I disable -98 nade  ty very much again
