### ISSUE TITLE
2 Errors occured

### ISSUE THREAD

**Issue by Zhxcky** [martinjanas/Sensum#96]
Sensum Version : Patch 1.5.2 (31 December 2019)
Problem : Severity	Code	Description	Project	File	Line	Suppression State	Suppression State
Error	C1189	#error:  The <experimental/filesystem> header providing std::experimental::filesystem is deprecated by Microsoft and will be REMOVED. It is superseded by the C++17 <filesystem> header providing std::filesystem. You can define _SILENCE_EXPERIMENTAL_FILESYSTEM_DEPRECATION_WARNING to acknowledge that you have received this warning.	Sensum	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\experimental\filesystem	26	

and also Severity	Code	Description	Project	File	Line	Suppression State	Suppression State
Error	C1189	#error:  The <experimental/filesystem> header providing std::experimental::filesystem is deprecated by Microsoft and will be REMOVED. It is superseded by the C++17 <filesystem> header providing std::filesystem. You can define _SILENCE_EXPERIMENTAL_FILESYSTEM_DEPRECATION_WARNING to acknowledge that you have received this warning.	Sensum	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\experimental\filesystem	26

**Comment by p1pS** [comment]
Refer to 90% of the closed issues, i.e #89 
> Do what it says, you have 2 choices:
> 1 (bad way). Define the silence thing:
> `#define _SILENCE_FILESYSTEM_DEPRECATION_WARNING`
> at the top of both files (config.cpp and options.cpp).
> OR
> 2 (the proper way). Change the `#include <experiemental/filesystem>` to `#include <filesystem>` and change the `namespace fs = std::experimental::filesystem;` to `namespace fs = std::filesystem;` in both files (config.cpp and options.cpp).
> Should work.

**Comment by Zhxcky** [comment]
> Refer to 90% of the closed issues, i.e #89
> 
> > Do what it says, you have 2 choices:
> > 1 (bad way). Define the silence thing:
> > `#define _SILENCE_FILESYSTEM_DEPRECATION_WARNING`
> > at the top of both files (config.cpp and options.cpp).
> > OR
> > 2 (the proper way). Change the `#include <experiemental/filesystem>` to `#include <filesystem>` and change the `namespace fs = std::experimental::filesystem;` to `namespace fs = std::filesystem;` in both files (config.cpp and options.cpp).
> > Should work.

Thanks, what about this? 1>C:\Desktop\Sensum Updated (CSGO)\Sensum-master\src\render\tabs\aimbot_tab.cpp(86,51): warning C4018: '>=': signed/unsigned mismatch

**Comment by martinjanas** [comment]
> > Refer to 90% of the closed issues, i.e #89
> > > Do what it says, you have 2 choices:
> > > 1 (bad way). Define the silence thing:
> > > `#define _SILENCE_FILESYSTEM_DEPRECATION_WARNING`
> > > at the top of both files (config.cpp and options.cpp).
> > > OR
> > > 2 (the proper way). Change the `#include <experiemental/filesystem>` to `#include <filesystem>` and change the `namespace fs = std::experimental::filesystem;` to `namespace fs = std::filesystem;` in both files (config.cpp and options.cpp).
> > > Should work.
> 
> Thanks, what about this? 1>C:\Desktop\Sensum Updated (CSGO)\Sensum-master\src\render\tabs\aimbot_tab.cpp(86,51): warning C4018: '>=': signed/unsigned mismatch

Thats just warning, you can ignore that.
