### ISSUE TITLE
ManualMap

### ISSUE THREAD

**Issue by AlexanderQueen** [martinjanas/Sensum#97]
Can you try to make it possible for MMAP injection?

**Comment by martinjanas** [comment]
It shouldn't make the difference if the injector is manual map or load library.

**Comment by AlexanderQueen** [comment]
Im not asking about injector. Im asking about method supported by cheat. It supports manualmap?

**Comment by martinjanas** [comment]
Why it wouldnt? You have problem injecting or what?
